apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-harbor-test
  labels:
    app: nginx-harbor-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-harbor-test
  template:
    metadata:
      labels:
        app: nginx-harbor-test
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: nginx
        image: 192.168.56.100:30002/library/nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-harbor-test-svc
  labels:
    app: nginx-harbor-test
spec:
  type: NodePort
  selector:
    app: nginx-harbor-test
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080